http:
  x_forwarded_for: false
  x_forwarded_proto: http
  x_request_start: true
  address: :8080
  check_interval: 5000
  discovery: etcd
  redirect:
    no_hostname: http://thebest404pageever.com/
    no_backend: http://404.jodi.org/
    error: http://500.chromeexperiments.com/

discovery:
  keyspace: knuckles
  hosts:
    - http://localhost:4001

statsd:
  address: localhost:8125
  prefix: knuckles.http.
