http:
  stunnel: false
  address: :8080
  check_interval: 5000
  redirect:
    no_hostname: http://thebest404pageever.com/
    no_backend: http://404.jodi.org/
    error: http://500.chromeexperiments.com/

redis:
  keyspace: knuckles
  hosts:
    - localhost:6379
    - localhost:6379
    - localhost:6379

statsd:
  address: localhost:8125
  prefix: knuckles.http.
